#ifndef DISPLAY_H
#define DISPLAY_H
void display();
void drawInnerMainBorder();
void drawLiteBlueOuter();
void drawOuterMainBorder();
void drawLiteBlueInner();
void LdrawInnerMainBorder();
void LdrawLiteRedOuter();
void LdrawOuterMainBorder();
void LdrawLiteRedInner();
void drawRightSideOuter();
void drawLeftSideOuter();
void drawInnerZameen();
void drawGreenLand();
void drawCenterCircleLine();
void rMainGround();
void lMainGround();
#endif 